server:
  port: 8080

spring:
  datasource:
    username: root
    password: Az1Sx2Dc3Fv4Gb5
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
      show-sql: true

# example values

indexing-settings:
  sites:
    - url: https://fabgroom-msk.ru
      name: Грумминг Москва
    - url: https://vok36.ru
      name: Офтальмологическая клиника Воронеж
    - url: https://ipfran.ru
      name: ИПФРАН