server:
  port: 8080

spring:
  datasource:
    username: root
    password: Az1Sx2Dc3Fv4Gb5
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
      show-sql: true

# example values

indexing-settings:
  sites:
    - url: https://fabgroom-msk.ru
      name: Грумминг Москва
    - url: https://sendel.ru
      name: Сайт Константина Шибкова
    - url: https://www.svetlovka.ru
      name: Светловка библиотека