server:
  port: 8090

spring:
  datasource:
    username: postgres
    password: Az1Sx2Dc3Fv4Gb5
    url: jdbc:postgresql://localhost:8080/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: none
      show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

# example values

indexing-settings:
  sites:
    - url: https://fabgroom-msk.ru
      name: Грумминг Москва
    - url: https://sendel.ru
      name: Сайт Константина Шибкова
    - url: https://www.svetlovka.ru
      name: Светловка библиотека